### ISSUE TITLE
项目完全无法使用

### ISSUE THREAD

**Issue by s-yh-china** [ShirosakiMieru/TencentSurveyApi#2]
很抱歉再次开一个issues,但是这个项目的最新版完全无法使用
各种奇怪的问题都出现了,就像是一个半成品?
然而历史版本是完成没有问题的

**Comment by ShirosakiMieru** [comment]
应该修复了。
这个项目确实是半成品，因为精力有限所以开发会有点慢，见谅
现在这个版本只能说是能用吧，之后可能要重构一哈（
编译好的jar放release里了
